name = "me"
main = "./.output/server/index.mjs"
compatibility_date = "2022-09-10"

workers_dev = true
route = { pattern = "borabuyukbas.com.tr/*", zone_name = "borabuyukbas.com.tr" }

[site]
bucket = ".output/public"
